name: qsar
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - ipykernel
  - nbstripout
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - rdkit
  - requests
  - openpyxl